### ISSUE TITLE
wrong datasheet for spi nor flash?

### ISSUE THREAD

**Issue by pabigot** [particle-iot/xenon#2]
The datasheets directory has a datasheet for the MX25L1606E, which was presumably the originally-planned 16 Mibit flash.  The 32 Mibit flash datasheet is for the GigaDevice GD25Q32C.  However, that device has a JEDEC id of 0xc84016.

The device in my Xenon has a JEDEC id of 0xc22016, which is a Macronix MX25L3205D.

The two devices are fairly close, but the GigaDevice promises significantly lower standby and deep power-down current consumption than Macronix.  Identifying the correct device explains some of the differences I'd noticed.

**Comment by pabigot** [comment]
Actually, it's more likely it's the MX25L3206E, which has the same JEDEC ID but supports QSPI.  (This also has different current consumption than GigaDevices, but matches the actual measurements much better.)

**Comment by pabigot** [comment]
Nope.  It's actually the MX25L3233F, based on the contents of the SFDP.

**Comment by rickkas7** [comment]
You are correct. It is the MX25L3233F and I removed the incorrect ones and added that one to the datasheets directory.
